USE master;
GO

CREATE DATABASE UNIVERCITY
ON PRIMARY
(
    NAME = N'UNIVERCITY1_mdf',
    FILENAME = N'D:\уник\UNIVERCITY1.mdf',
    SIZE = 10240KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024KB
),
(
    NAME = N'UNIVERCITY1_ndf',
    FILENAME = N'D:\уник\UNIVERCITY1.ndf',
    SIZE = 10240KB,
    MAXSIZE = 1GB,
    FILEGROWTH = 25%
),
FILEGROUP FG1
(
    NAME = N'UNIVERCITY1_fg1_1',
    FILENAME = N'D:\уник\UNIVERCITY1_fg1_1.ndf',
    SIZE = 10240KB,
    MAXSIZE = 1GB,
    FILEGROWTH = 25%
),
(
    NAME = N'UNIVERCITY1_fg1_2',
    FILENAME = N'D:\уник\UNIVERCITY1_fg1_2.ndf',
    SIZE = 10240KB,
    MAXSIZE = 1GB,
    FILEGROWTH = 25%
)
LOG ON
(
    NAME = N'UNIVERCITY1_log',
    FILENAME = N'D:\уник\UNIVERCITY1.ldf',
    SIZE = 10240KB,
    MAXSIZE = 2048GB,
    FILEGROWTH = 10%
);
GO